/* Elo rating for a Chess Club
Copyright (C) 2023 - 2026  Lluís Alemany Puig

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

Full source code of elo-chess-tracker:
	https://github.com/lluisalemanypuig/elo-chess-tracker

Contact:
	Lluís Alemany Puig
	https://github.com/lluisalemanypuig
*/

import { UserRole } from '@common/models/user-role';
import { z } from 'zod';

// -----------------------------------------------------------------------------

export const ALL_ACTIONS = [
	'CREATE_USER',

	'CREATE_GAMES',
	'CREATE_GAMES_ADMIN',
	'CREATE_GAMES_REFEREE',
	'CREATE_GAMES_TEACHER',
	'CREATE_GAMES_MEMBER',
	'CREATE_GAMES_STUDENT',

	'EDIT_GAMES',
	'EDIT_GAMES_ADMIN',
	'EDIT_GAMES_REFEREE',
	'EDIT_GAMES_TEACHER',
	'EDIT_GAMES_MEMBER',
	'EDIT_GAMES_STUDENT',

	'DELETE_GAMES',
	'DELETE_GAMES_ADMIN',
	'DELETE_GAMES_REFEREE',
	'DELETE_GAMES_TEACHER',
	'DELETE_GAMES_MEMBER',
	'DELETE_GAMES_STUDENT',

	'SEE_GAMES',
	'SEE_GAMES_ADMIN',
	'SEE_GAMES_REFEREE',
	'SEE_GAMES_TEACHER',
	'SEE_GAMES_MEMBER',
	'SEE_GAMES_STUDENT',

	'EDIT_USER',
	'EDIT_USER_ADMIN',
	'EDIT_USER_REFEREE',
	'EDIT_USER_TEACHER',
	'EDIT_USER_MEMBER',
	'EDIT_USER_STUDENT',

	'ASSIGN_ROLE',
	'ASSIGN_ROLE_ADMIN',
	'ASSIGN_ROLE_REFEREE',
	'ASSIGN_ROLE_TEACHER',
	'ASSIGN_ROLE_MEMBER',
	'ASSIGN_ROLE_STUDENT',

	'SEE_GRAPHS',
	'SEE_GRAPHS_ADMIN',
	'SEE_GRAPHS_REFEREE',
	'SEE_GRAPHS_TEACHER',
	'SEE_GRAPHS_MEMBER',
	'SEE_GRAPHS_STUDENT',

	'CHALLENGE_USER',
	'CHALLENGE_USER_ADMIN',
	'CHALLENGE_USER_REFEREE',
	'CHALLENGE_USER_TEACHER',
	'CHALLENGE_USER_MEMBER',
	'CHALLENGE_USER_STUDENT',

	'FORCE_CHALLENGE_ACCEPT',
	'FORCE_CHALLENGE_ACCEPT_ADMIN',
	'FORCE_CHALLENGE_ACCEPT_REFEREE',
	'FORCE_CHALLENGE_ACCEPT_TEACHER',
	'FORCE_CHALLENGE_ACCEPT_MEMBER',
	'FORCE_CHALLENGE_ACCEPT_STUDENT',

	'FORCE_CHALLENGE_SET_RESULT',
	'FORCE_CHALLENGE_SET_RESULT_ADMIN',
	'FORCE_CHALLENGE_SET_RESULT_REFEREE',
	'FORCE_CHALLENGE_SET_RESULT_TEACHER',
	'FORCE_CHALLENGE_SET_RESULT_MEMBER',
	'FORCE_CHALLENGE_SET_RESULT_STUDENT',

	'FORCE_CHALLENGE_ACCEPT_RESULT',
	'FORCE_CHALLENGE_ACCEPT_RESULT_ADMIN',
	'FORCE_CHALLENGE_ACCEPT_RESULT_REFEREE',
	'FORCE_CHALLENGE_ACCEPT_RESULT_TEACHER',
	'FORCE_CHALLENGE_ACCEPT_RESULT_MEMBER',
	'FORCE_CHALLENGE_ACCEPT_RESULT_STUDENT',
] as const;

export type UserAction = (typeof ALL_ACTIONS)[number];

export const UserActionSchema = z.enum(ALL_ACTIONS);

export const UserActionArraySchema = z.array(UserActionSchema);

// -----------------------------------------------------------------------------

export const ALL_ACTION_IDS = [
	'CREATE_GAMES',
	'EDIT_GAMES',
	'DELETE_GAMES',
	'EDIT_USERS',
	'ASSIGN_ROLE_USERS',
	'CHALLENGE_USERS',
	'SEE_GAMES',
	'SEE_GRAPHS',
	'FORCE_CHALLENGE_ACCEPT',
	'FORCE_CHALLENGE_SET_RESULT',
	'FORCE_CHALLENGE_ACCEPT_RESULT',
] as const;

export type UserActionId = (typeof ALL_ACTION_IDS)[number];

export const UserActionIDSchema = z.enum(ALL_ACTION_IDS);

export const userActionIdToUserAction: Record<UserActionId, UserAction> = {
	CREATE_GAMES: 'CREATE_GAMES',
	EDIT_GAMES: 'EDIT_GAMES',
	DELETE_GAMES: 'DELETE_GAMES',
	SEE_GAMES: 'SEE_GAMES',
	EDIT_USERS: 'EDIT_USER',
	ASSIGN_ROLE_USERS: 'ASSIGN_ROLE',
	CHALLENGE_USERS: 'CHALLENGE_USER',
	SEE_GRAPHS: 'SEE_GRAPHS',
	FORCE_CHALLENGE_ACCEPT: 'FORCE_CHALLENGE_ACCEPT',
	FORCE_CHALLENGE_SET_RESULT: 'FORCE_CHALLENGE_SET_RESULT',
	FORCE_CHALLENGE_ACCEPT_RESULT: 'FORCE_CHALLENGE_ACCEPT_RESULT',
};

export const roleActionNames: Record<
	UserActionId,
	Record<UserRole, UserAction>
> = {
	CREATE_GAMES: {
		ADMIN: 'CREATE_GAMES_ADMIN',
		REFEREE: 'CREATE_GAMES_REFEREE',
		TEACHER: 'CREATE_GAMES_TEACHER',
		MEMBER: 'CREATE_GAMES_MEMBER',
		STUDENT: 'CREATE_GAMES_STUDENT',
	},
	EDIT_GAMES: {
		ADMIN: 'EDIT_GAMES_ADMIN',
		REFEREE: 'EDIT_GAMES_REFEREE',
		TEACHER: 'EDIT_GAMES_TEACHER',
		MEMBER: 'EDIT_GAMES_MEMBER',
		STUDENT: 'EDIT_GAMES_STUDENT',
	},
	DELETE_GAMES: {
		ADMIN: 'DELETE_GAMES_ADMIN',
		REFEREE: 'DELETE_GAMES_REFEREE',
		TEACHER: 'DELETE_GAMES_TEACHER',
		MEMBER: 'DELETE_GAMES_MEMBER',
		STUDENT: 'DELETE_GAMES_STUDENT',
	},
	SEE_GAMES: {
		ADMIN: 'SEE_GAMES_ADMIN',
		REFEREE: 'SEE_GAMES_REFEREE',
		TEACHER: 'SEE_GAMES_TEACHER',
		MEMBER: 'SEE_GAMES_MEMBER',
		STUDENT: 'SEE_GAMES_STUDENT',
	},
	EDIT_USERS: {
		ADMIN: 'EDIT_USER_ADMIN',
		REFEREE: 'EDIT_USER_REFEREE',
		TEACHER: 'EDIT_USER_TEACHER',
		MEMBER: 'EDIT_USER_MEMBER',
		STUDENT: 'EDIT_USER_STUDENT',
	},
	ASSIGN_ROLE_USERS: {
		ADMIN: 'ASSIGN_ROLE_ADMIN',
		REFEREE: 'ASSIGN_ROLE_REFEREE',
		TEACHER: 'ASSIGN_ROLE_TEACHER',
		MEMBER: 'ASSIGN_ROLE_MEMBER',
		STUDENT: 'ASSIGN_ROLE_STUDENT',
	},
	CHALLENGE_USERS: {
		ADMIN: 'CHALLENGE_USER_ADMIN',
		REFEREE: 'CHALLENGE_USER_REFEREE',
		TEACHER: 'CHALLENGE_USER_TEACHER',
		MEMBER: 'CHALLENGE_USER_MEMBER',
		STUDENT: 'CHALLENGE_USER_STUDENT',
	},
	SEE_GRAPHS: {
		ADMIN: 'SEE_GRAPHS_ADMIN',
		REFEREE: 'SEE_GRAPHS_REFEREE',
		TEACHER: 'SEE_GRAPHS_TEACHER',
		MEMBER: 'SEE_GRAPHS_MEMBER',
		STUDENT: 'SEE_GRAPHS_STUDENT',
	},
	FORCE_CHALLENGE_ACCEPT: {
		ADMIN: 'FORCE_CHALLENGE_ACCEPT_ADMIN',
		REFEREE: 'FORCE_CHALLENGE_ACCEPT_REFEREE',
		TEACHER: 'FORCE_CHALLENGE_ACCEPT_TEACHER',
		MEMBER: 'FORCE_CHALLENGE_ACCEPT_MEMBER',
		STUDENT: 'FORCE_CHALLENGE_ACCEPT_STUDENT',
	},
	FORCE_CHALLENGE_SET_RESULT: {
		ADMIN: 'FORCE_CHALLENGE_SET_RESULT_ADMIN',
		REFEREE: 'FORCE_CHALLENGE_SET_RESULT_REFEREE',
		TEACHER: 'FORCE_CHALLENGE_SET_RESULT_TEACHER',
		MEMBER: 'FORCE_CHALLENGE_SET_RESULT_MEMBER',
		STUDENT: 'FORCE_CHALLENGE_SET_RESULT_STUDENT',
	},
	FORCE_CHALLENGE_ACCEPT_RESULT: {
		ADMIN: 'FORCE_CHALLENGE_ACCEPT_RESULT_ADMIN',
		REFEREE: 'FORCE_CHALLENGE_ACCEPT_RESULT_REFEREE',
		TEACHER: 'FORCE_CHALLENGE_ACCEPT_RESULT_TEACHER',
		MEMBER: 'FORCE_CHALLENGE_ACCEPT_RESULT_MEMBER',
		STUDENT: 'FORCE_CHALLENGE_ACCEPT_RESULT_STUDENT',
	},
};

export const actionIdToUserActions: { [key in UserActionId]: UserAction[] } = {
	CREATE_GAMES: [
		'CREATE_GAMES_ADMIN',
		'CREATE_GAMES_REFEREE',
		'CREATE_GAMES_TEACHER',
		'CREATE_GAMES_MEMBER',
		'CREATE_GAMES_STUDENT',
	],
	DELETE_GAMES: [
		'DELETE_GAMES_ADMIN',
		'DELETE_GAMES_REFEREE',
		'DELETE_GAMES_TEACHER',
		'DELETE_GAMES_MEMBER',
		'DELETE_GAMES_STUDENT',
	],
	EDIT_USERS: [
		'EDIT_USER_ADMIN',
		'EDIT_USER_REFEREE',
		'EDIT_USER_TEACHER',
		'EDIT_USER_MEMBER',
		'EDIT_USER_STUDENT',
	],
	EDIT_GAMES: [
		'EDIT_GAMES_ADMIN',
		'EDIT_GAMES_REFEREE',
		'EDIT_GAMES_TEACHER',
		'EDIT_GAMES_MEMBER',
		'EDIT_GAMES_STUDENT',
	],
	ASSIGN_ROLE_USERS: [
		'ASSIGN_ROLE_ADMIN',
		'ASSIGN_ROLE_REFEREE',
		'ASSIGN_ROLE_TEACHER',
		'ASSIGN_ROLE_MEMBER',
		'ASSIGN_ROLE_STUDENT',
	],
	SEE_GAMES: [
		'SEE_GAMES_ADMIN',
		'SEE_GAMES_REFEREE',
		'SEE_GAMES_TEACHER',
		'SEE_GAMES_MEMBER',
		'SEE_GAMES_STUDENT',
	],
	SEE_GRAPHS: [
		'SEE_GRAPHS_ADMIN',
		'SEE_GRAPHS_REFEREE',
		'SEE_GRAPHS_TEACHER',
		'SEE_GRAPHS_MEMBER',
		'SEE_GRAPHS_STUDENT',
	],
	CHALLENGE_USERS: [
		'CHALLENGE_USER_ADMIN',
		'CHALLENGE_USER_REFEREE',
		'CHALLENGE_USER_TEACHER',
		'CHALLENGE_USER_MEMBER',
		'CHALLENGE_USER_STUDENT',
	],
	FORCE_CHALLENGE_ACCEPT: [
		'FORCE_CHALLENGE_ACCEPT_ADMIN',
		'FORCE_CHALLENGE_ACCEPT_REFEREE',
		'FORCE_CHALLENGE_ACCEPT_TEACHER',
		'FORCE_CHALLENGE_ACCEPT_MEMBER',
		'FORCE_CHALLENGE_ACCEPT_STUDENT',
	],
	FORCE_CHALLENGE_SET_RESULT: [
		'FORCE_CHALLENGE_SET_RESULT_ADMIN',
		'FORCE_CHALLENGE_SET_RESULT_REFEREE',
		'FORCE_CHALLENGE_SET_RESULT_TEACHER',
		'FORCE_CHALLENGE_SET_RESULT_MEMBER',
		'FORCE_CHALLENGE_SET_RESULT_STUDENT',
	],
	FORCE_CHALLENGE_ACCEPT_RESULT: [
		'FORCE_CHALLENGE_ACCEPT_RESULT_ADMIN',
		'FORCE_CHALLENGE_ACCEPT_RESULT_REFEREE',
		'FORCE_CHALLENGE_ACCEPT_RESULT_TEACHER',
		'FORCE_CHALLENGE_ACCEPT_RESULT_MEMBER',
		'FORCE_CHALLENGE_ACCEPT_RESULT_STUDENT',
	],
};
